### ISSUE TITLE
A training error on CIFAR10?

### ISSUE THREAD

**Issue by chenfsjz** [rdevon/DIM#11]
hi! When I try to retrain the DIM on CIFAR10, there is an issue in the project:
    
     Traceback (most recent call last):
     File "scripts/deep_infomax.py", line 227, in <module>
       run(DIM())
      File "/usr/local/lib/python3.5/dist-packages/cortex/main.py", line 38, in run
        data.setup(**exp.ARGS['data'])
      File "/usr/local/lib/python3.5/dist-packages/cortex/_lib/data/__init__.py", line 69, in setup
    plugin.handle(source, **data_args_)
      File "/usr/local/lib/python3.5/dist-packages/cortex/built_ins/datasets/torchvision_datasets.py", 
    line 142, in handle
    uniques = sorted(np.unique(labels).tolist())
    UnboundLocalError: local variable 'labels' referenced before assignment

I install the cortex as your readme.txt and the version is cortex-0.13, when I check the source code of the specific line in torchvision_datasets.py, there seems the labels is not contained in the CIFAR10 dataset.

    train_set, test_set = handler(Dataset, data_path, transform=train_transform, test_transform=test_transform,
                                      labeled_only=labeled_only)
        if train_samples is not None:
            train_set.train_data = train_set.train_data[:train_samples]
            train_set.train_labels = train_set.train_labels[:train_samples]
        if test_samples is not None:
            test_set.test_data = test_set.test_data[:test_samples]
            test_set.test_labels = test_set.test_labels[:test_samples]

        dim_images = train_set[0][0].size()

        if hasattr(train_set, 'labels'):
            labels = train_set.labels
        elif hasattr(train_set, 'targets'):
            labels = train_set.targets

        uniques = sorted(np.unique(labels).tolist())

        if -1 in uniques:
            uniques = uniques[1:]

        dim_l = len(uniques)
        dims = dict(images=dim_images, targets=dim_l)
        input_names = ['images', 'targets', 'index']

        self.add_dataset(
            source,
            data=dict(train=train_set, test=test_set),
            input_names=input_names,
            dims=dims,
            scale=scale

**Comment by rdevon** [comment]
So the problem is that cortex dev has moved a bit since I last pushed this repo. I'm working on updating DIM, but I ran into some snags that I should be wrapping up this week.

DIM should be up-to-date with the latest cortex later this week, but until then you should be using this commit:
https://github.com/rdevon/cortex/tree/07646b8cde28b898caba649bf1d93719ad539b98

Let me know if that works. I'm making this a priority this week, so at least by the end of the week things should be working again.

**Comment by chenfsjz** [comment]
Thanks for your reply, After I install the new version of cortex, there is a new issue as below,
    
    run(DIM())
    File "/usr/local/lib/python3.5/dist-packages/cortex/main.py", line 26, in run
      args = setup_cortex(model=model)
    File "/usr/local/lib/python3.5/dist-packages/cortex/_lib/__init__.py", line 32, in setup_cortex
     args = parse_args(models.MODEL_PLUGINS, model=model)
    File "/usr/local/lib/python3.5/dist-packages/cortex/_lib/parsing.py", line 379, in parse_args
       _parse_model(model, parser)
     File "/usr/local/lib/python3.5/dist-packages/cortex/_lib/parsing.py", line 257, in _parse_model
       _add_default_arguments(key, args, subparser)
     File "/usr/local/lib/python3.5/dist-packages/cortex/_lib/parsing.py", line 273, in 
        _add_default_arguments
    help = DEFAULT_HELP[key][k]
    KeyError: 'model'

**Comment by rdevon** [comment]
OK, that's strange. Obviously I need to work out which version is working. I can test this out on Monday (or just push some fixes).

**Comment by rdevon** [comment]
I've pushed a lot of changes. Things should work now, and there are more features.
https://github.com/rdevon/DIM/commit/e6622e1de4dc9e15ab4fbb8f72ad495a813e780e

Let me know if your problems in this issue are fixed.

**Comment by chenfsjz** [comment]
I guess there is some thing has been missed?

    ImportError: No module named 'cortex_DIM.evaluation_models.mine_eval'

so you forgot  to upload the mine_eval into the evaluation_models?

**Comment by rdevon** [comment]
Ah. No I meant to exclude it. Will fix ASAP but weird the error didn't come up for me in a fresh env

**Comment by rdevon** [comment]
Hopefully https://github.com/rdevon/DIM/commit/1242330eb8d10e292978b0bfb7ba3db440943a3f fixed it. I wont have time to test it until Monday.

**Comment by yuu-Wang** [comment]
> hi! When I try to retrain the DIM on CIFAR10, there is an issue in the project:
> 
> ```
>  Traceback (most recent call last):
>  File "scripts/deep_infomax.py", line 227, in <module>
>    run(DIM())
>   File "/usr/local/lib/python3.5/dist-packages/cortex/main.py", line 38, in run
>     data.setup(**exp.ARGS['data'])
>   File "/usr/local/lib/python3.5/dist-packages/cortex/_lib/data/__init__.py", line 69, in setup
> plugin.handle(source, **data_args_)
>   File "/usr/local/lib/python3.5/dist-packages/cortex/built_ins/datasets/torchvision_datasets.py", 
> line 142, in handle
> uniques = sorted(np.unique(labels).tolist())
> UnboundLocalError: local variable 'labels' referenced before assignment
> ```
> 
> I install the cortex as your readme.txt and the version is cortex-0.13, when I check the source code of the specific line in torchvision_datasets.py, there seems the labels is not contained in the CIFAR10 dataset.
> 
> ```
> train_set, test_set = handler(Dataset, data_path, transform=train_transform, test_transform=test_transform,
>                                   labeled_only=labeled_only)
>     if train_samples is not None:
>         train_set.train_data = train_set.train_data[:train_samples]
>         train_set.train_labels = train_set.train_labels[:train_samples]
>     if test_samples is not None:
>         test_set.test_data = test_set.test_data[:test_samples]
>         test_set.test_labels = test_set.test_labels[:test_samples]
> 
>     dim_images = train_set[0][0].size()
> 
>     if hasattr(train_set, 'labels'):
>         labels = train_set.labels
>     elif hasattr(train_set, 'targets'):
>         labels = train_set.targets
> 
>     uniques = sorted(np.unique(labels).tolist())
> 
>     if -1 in uniques:
>         uniques = uniques[1:]
> 
>     dim_l = len(uniques)
>     dims = dict(images=dim_images, targets=dim_l)
>     input_names = ['images', 'targets', 'index']
> 
>     self.add_dataset(
>         source,
>         data=dict(train=train_set, test=test_set),
>         input_names=input_names,
>         dims=dims,
>         scale=scale
> `您好，想问一下这个代码为什么会出现这个错误，不知道如何解决：Traceback (most recent call last):
  File "scripts/main.py", line 71, in <module>
    run(controller)
  File "/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/cortex/main.py", line 39, in run
    model.build()
  File "/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/cortex/_lib/models.py", line 417, in wrapped
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/cortex_DIM/models/controller.py", line 216, in build
    model.build(self.encoder, copy.deepcopy(config))
  File "/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/cortex/_lib/models.py", line 417, in wrapped
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/cortex_DIM/evaluation_models/classification_eval.py", line 49, in build
    X = self.inputs('data.images')
  File "/root/anaconda3/envs/pytorch_2.2.1/lib/python3.8/site-packages/cortex_DIM/models/controller.py", line 140, in get_inputs
    raise KeyError(f"Input key '{key}' not found in inputs dictionary.")
KeyError: "Input key 'data.images' not found in inputs dictionary."
您能帮忙看一下吗
